name: Build & Test

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.x
      - name: restore dependencies
        run: dotnet restore ./BookManager/BookManager.csproj
      - name: build
        run: dotnet build ./BookManager/BookManager.csproj --no-restore
      - name: test
        run: dotnet test ./BookManager/BookManager.csproj --no-build --verbosity normal
